name = "presskit-worker"
compatibility_date = "2024-07-12"
main = "src/index.tsx"

[site]
bucket = "./public"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "page_cache"
id = "e96508e82717498584c7ccd03ba8469f"
preview_id = "3df9af57bd124086bc0cf93e9eb206fd"
