name = "presskit-worker"
compatibility_date = "2024-11-06"
assets = { directory = "../../public" }
main = "src/index.tsx"

[build]
command = "pnpm build:css"

# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# see .dev.env for local vars and secrets
# export GH_PAT=<GitHub-token>
# export IMAGE_KEY=<image-hash-key>

[vars]
ENVIRONMENT = "prod"
GH_OWNER = "jldec"
GH_REPO = "presskit"
GH_BRANCH = "main"
GH_PATH = "src/dev/content"

[ai]
binding = "AI"

[[r2_buckets]]
# pnpm wrangler r2 bucket create presskit-img-v0
binding = 'IMAGES'
bucket_name = 'presskit-img-v0'
preview_bucket_name = 'presskit-img-v0-preview'

[[kv_namespaces]]
# pnpm wrangler kv namespace create PAGEDATA_CACHE
# pnpm wrangler kv namespace create PAGEDATA_CACHE --preview
binding = "PAGEDATA_CACHE"
id = "059d93f832ac4eb1b0bee87420399a54"
preview_id = "c779ce3d69754eb297b6e97e1aaaeebf"

[[kv_namespaces]]
# pnpm wrangler kv namespace create STATIC_CACHE
# pnpm wrangler kv namespace create STATIC_CACHE --preview
binding = "STATIC_CACHE"
id = "d8be0bcc47684c2899d45d2d6a808482"
preview_id = "66dcef1314bb4265b9c960e6647a30bd"

[durable_objects]
bindings = [{ name = "CHATS", class_name = "Party" }]

[[migrations]]
tag = "v1"
new_classes = ["Chat"]

[[migrations]]
tag = "v2"
new_classes = ["PagePrep"]

[[migrations]]
tag = "v3"
renamed_classes = [
  { from = "Chat", to = "Party" },
  { from = "PagePrep", to = "Page" },
]

[[migrations]]
tag = "v4"
deleted_classes = ["Page"]
