name = "presskit-worker"
compatibility_date = "2024-07-12"
main = "src/index.tsx"
compatibility_flags = ["nodejs_compat_v2"]

# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# secrets - pnpm wrangler secret put <GH_PAT etc>
# ENVIRONMENT: prod
# APP_URL: https://presskit.jldec.me/
# GH_PAT: Expires on Mon, Dec 16 2024
# GH_REPO: jldec/presskit
# IMAGE_KEY: no expiration

[site]
bucket = "../../public"

[ai]
binding = "AI"

[[r2_buckets]]
# pnpm wrangler r2 bucket create presskit-img-v0
binding = 'IMAGES'
bucket_name = 'presskit-img-v0'
preview_bucket_name = 'presskit-img-v0-preview'

[[kv_namespaces]]
# pnpm wrangler kv namespace create PAGE_CACHE
# pnpm wrangler kv namespace create PAGE_CACHE --preview
binding = "PAGE_CACHE"
id = "65c4126075304a93baaacea9187ff8a9"
preview_id = "b52a7190959c4127b32cd717b9aa8936"

[durable_objects]
bindings = [
  { name = "CHATS", class_name = "Party" },
  { name = "PAGES", class_name = "Page" },
]

[[migrations]]
tag = "v1"
new_classes = ["Chat"]

[[migrations]]
tag = "v2"
new_classes = ["PagePrep"]

[[migrations]]
tag = "v3"
renamed_classes = [
  { from = "Chat", to = "Party" },
  { from = "PagePrep", to = "Page" },
]
