name = "jldec-worker"
compatibility_date = "2025-03-21"
assets = { directory = "../../public" }
main = "src/index.tsx"

[build]
command = "pnpm build:css"

# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# see .dev.env for local vars and secrets
# export GH_PAT=<GitHub-token>
# export IMAGE_KEY=<image-hash-key>

[vars]
ENVIRONMENT = "prod"
GH_OWNER = "jldec"
GH_REPO = "jldec-me"
GH_BRANCH = "main"
GH_PATH = "content"
DEBUG = "true"

[ai]
binding = "AI"

[[r2_buckets]]
# pnpm wrangler -c wrangler-jldec.toml r2 bucket create jldec-img-v0
binding = "IMAGES"
bucket_name = "jldec-img-v0"
preview_bucket_name = "presskit-img-v0-preview"

[[kv_namespaces]]
# pnpm wrangler -c wrangler-jldec.toml kv namespace create PAGEDATA_CACHE
# pnpm wrangler -c wrangler-jldec.toml kv namespace create PAGEDATA_CACHE --preview
binding = "PAGEDATA_CACHE"
id = "5f8d80af855f41ecbfc5979785c3a198"
preview_id = "bffac0aa358e427caf02baa3b1bd3dcf"

[[kv_namespaces]]
# pnpm wrangler -c wrangler-jldec.toml kv namespace create STATIC_CACHE
# pnpm wrangler -c wrangler-jldec.toml kv namespace create STATIC_CACHE --preview
binding = "STATIC_CACHE"
id = "de412f0f798b4841824f93b39b5ff42a"
preview_id = "f4f7c70da99e4d6bbdf7c71a1a229cfa"

[durable_objects]
bindings = [{ name = "CHATS", class_name = "Party" }]

[[migrations]]
tag = "v1"
new_classes = ["Party"]
