name = "presskit-worker"
compatibility_date = "2024-07-12"
main = "src/index.tsx"

# secrets
# GH_PAT: Expires on Mon, Sep 16 2024
# IMAGE_KEY: no expiration

[site]
bucket = "../../public"

[ai]
binding = "AI"

[[r2_buckets]]
# pnpm wrangler r2 bucket create presskit-img-v0
binding = 'IMAGES'
bucket_name = 'presskit-img-v0'

[[kv_namespaces]]
# pnpm wrangler kv namespace create PAGE_CACHE
# pnpm wrangler kv namespace create PAGE_CACHE --preview
binding = "PAGE_CACHE"
id = "65c4126075304a93baaacea9187ff8a9"
preview_id = "b52a7190959c4127b32cd717b9aa8936"

[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Chat"]
