name = "dev-content"
compatibility_date = "2024-09-25"
assets = { directory = "./content" }
main = "./index.js"

[vars]
SOURCE_PREFIX = "http://localhost:8765"

[dev]
port = 8765

[build]
command = "node build-manifest.js"